version: "3"

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:10000"
        networks:
            - web-app-network
    mongodb:
        image: mongo
        networks: 
            - web-app-network

networks:
    web-app-network:
        driver: bridge

        