export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
export const ERROR_FETCHING_PRODUCTS = 'ERROR_FETCHING_PRODUCTS';

export const FETCHING_PRODUCT_DETAILS = 'FETCHING_PRODUCT_DETAILS';
export const FETCHED_PRODUCT_DETAILS = 'FETCHED_PRODUCT_DETAILS';
export const ERROR_FETCHING_PRODUCT_DETAILS = 'ERROR_FETCHING_PRODUCT_DETAILS';

export const FETCHING_REVIEWS = 'FETCHING_REVIEWS';
export const FETCHED_REVIEWS = 'FETCHED_REVIEWS';
export const ERROR_FETCHING_REVIEWS = 'ERROR_FETCHING_REVIEWS';